server:
  port: 7003
spring:
  application:
    name: rabbitmq-consumer-2
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        prefetch: 10
        concurrency: 1
        max-concurrency: 3
        acknowledge-mode: manual
  redis:
    host: 127.0.0.1
    port: 6379
#    password: amber
